# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseA.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowA(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 288)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Label = QtWidgets.QRadioButton(self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(40, 90, 111, 17))
        self.Label.setObjectName("Label")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Label)
        self.girvan = QtWidgets.QRadioButton(self.centralwidget)
        self.girvan.setGeometry(QtCore.QRect(40, 130, 101, 17))
        self.girvan.setObjectName("girvan")
        self.buttonGroup.addButton(self.girvan)
        self.cont = QtWidgets.QRadioButton(self.centralwidget)
        self.cont.setGeometry(QtCore.QRect(160, 130, 81, 17))
        self.cont.setObjectName("cont")
        self.buttonGroup.addButton(self.cont)
        self.kmeans = QtWidgets.QRadioButton(self.centralwidget)
        self.kmeans.setGeometry(QtCore.QRect(160, 80, 82, 31))
        self.kmeans.setObjectName("kmeans")
        self.buttonGroup.addButton(self.kmeans)
        self.titre = QtWidgets.QLabel(self.centralwidget)
        self.titre.setGeometry(QtCore.QRect(50, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titre.setFont(font)
        self.titre.setObjectName("titre")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 210, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Louvain = QtWidgets.QRadioButton(self.centralwidget)
        self.Louvain.setGeometry(QtCore.QRect(40, 170, 101, 17))
        self.Louvain.setObjectName("Louvain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 293, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label.setText(_translate("MainWindow", "Label Propagation"))
        self.girvan.setText(_translate("MainWindow", "Girvan newman"))
        self.cont.setText(_translate("MainWindow", "Contribution"))
        self.kmeans.setText(_translate("MainWindow", "K means"))
        self.titre.setText(_translate("MainWindow", "Choose an algorithm"))
        self.pushButton.setText(_translate("MainWindow", "Execute"))
        self.pushButton_2.setText(_translate("MainWindow", "Run tests"))
        self.Louvain.setText(_translate("MainWindow", "Louvain"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowA()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
