# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading
def algo(num):
    if(num==1):
        for i in range (1000000000000):
            print("label propagation")
    elif(num==2):
        print("hello")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.LabelPropagation = QtWidgets.QRadioButton(self.centralwidget)
        self.LabelPropagation.setGeometry(QtCore.QRect(70, 150, 121, 17))
        self.LabelPropagation.setChecked(True)
        self.LabelPropagation.setObjectName("LabelPropagation")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.LabelPropagation)
        self.LabelPropagationC = QtWidgets.QRadioButton(self.centralwidget)
        self.LabelPropagationC.setGeometry(QtCore.QRect(70, 180, 201, 17))
        self.LabelPropagationC.setObjectName("LabelPropagationC")
        self.buttonGroup.addButton(self.LabelPropagationC)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(70, 210, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(70, 240, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(70, 270, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 180, 21, 16))
        self.label_2.setObjectName("label_2")
        self.KLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.KLabel.setGeometry(QtCore.QRect(340, 180, 21, 20))
        self.KLabel.setText("")
        self.KLabel.setObjectName("KLabel")
        self.Kmeans = QtWidgets.QLineEdit(self.centralwidget)
        self.Kmeans.setGeometry(QtCore.QRect(190, 270, 21, 20))
        self.Kmeans.setText("")
        self.Kmeans.setObjectName("Kmeans")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 270, 21, 16))
        self.label_3.setObjectName("label_3")
        self.TLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.TLabel.setGeometry(QtCore.QRect(400, 180, 21, 20))
        self.TLabel.setText("")
        self.TLabel.setObjectName("TLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 180, 21, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(450, 130, 21, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(140, 116, 321, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 329, 451, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 192, 47, 21))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 190, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Validate = QtWidgets.QPushButton(self.centralwidget)
        self.Validate.setGeometry(QtCore.QRect(360, 380, 75, 23))
        self.Validate.setObjectName("Validate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        global selected
        selected=1
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Algorihtme de détection :"))
        self.LabelPropagation.setText(_translate("MainWindow", "Label Propagation"))
        self.LabelPropagationC.setText(_translate("MainWindow", "Label Propagation avec contribution"))
        self.radioButton_3.setText(_translate("MainWindow", "Louvain"))
        self.radioButton_4.setText(_translate("MainWindow", "Spectral"))
        self.radioButton_5.setText(_translate("MainWindow", "K means"))
        self.label_2.setText(_translate("MainWindow", "K="))
        self.label_3.setText(_translate("MainWindow", "K="))
        self.label_4.setText(_translate("MainWindow", "T="))
        self.label_5.setText(_translate("MainWindow", "Réseau :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Karate"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Autre"))
        self.Validate.setText(_translate("MainWindow", "Exectuer"))
        self.LabelPropagation.clicked.connect(lambda:self.checks(1))
        self.LabelPropagationC.clicked.connect(lambda:self.checks(2))
        self.Validate.clicked.connect(self.checking)
    def checking(self):
        global selected
        t1 = threading.Thread(target=algo, args=(selected,))
        t1.start()

        
    def checks(self,value):
         global selected
         selected=value
         


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    
    MainWindow.show()
    b=True
    
           
    sys.exit(app.exec_())
